// This is a placeholder file — replace with your actual AWS Amplify config
// Generated by `amplify push` or `amplify init`

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_appsync_graphqlEndpoint: 'https://example.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
  aws_cognito_identity_pool_id: 'us-east-1:xxxxxx',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_xxxxxx',
  aws_user_pools_web_client_id: 'xxxxxx',
  aws_user_files_s3_bucket: 'xxxxxx',
  aws_user_files_s3_bucket_region: 'us-east-1'
}

export default awsmobile
